### PR TITLE
Design fix

### PR DESCRIPTION
**Pull request by ZalanZubik**

### CODE REVIEW

**Review by sarkiroka — CHANGES_REQUESTED** [review]
Thanks for everything, the changes so far look good for the most part! 
If you didn't plan anything else in this pull request, I'd have a couple of notes:

1. could you increase the size of the close button a bit? It was already reduced in a previous commit (https://github.com/shiwaforce/total-tutorial/commit/7a78930e4b5218da43cf335959244c396a426a1a#diff-45575bc47444219ccf8f1f08fbd10d45f17a3f5be63fe1d679da1026b9c04ee6), and now it looks stretched compared to the headline. Also, they are not aligned. More specifically, it is aligned with the top of the text, giving it a wobbly feel.
2 I'm glad you fixed the navigation bar offset, it's much nicer. But remember there is an admin interface too. Could you take a look at it, because I have a feeling that it's not all there yet.
3. In the same admin interface, the centering of the boxes on the screen still leaves something to be desired.
4. Great to see the increased storage in the highlighted section. Follow this on the admin as well for the element pick function!
5. When downloading the admin results, the script block to be inserted is really sticking to the edge, it needs spacing.
6. +1 Could you increase the rounding of the highlighted area a bit? Currently a bit pointy

**Comment by olilen** [comment]
Thank you for your recommendations, I've fixed the parts of the code that you've mentioned in your last comment, also I made the left edge of the explanation box run in line with the highlighted box's edge.

If you have any more recommendations or notice any more problems with the code that you want me to fix, feel free to comment.

**Review by sarkiroka — CHANGES_REQUESTED** [review]
Thank you very much for the further corrections. I assure you that your efforts are greatly appreciated.

I added a few "t" letters to one of the titles, and it looks like the close icon is not aligned, but lower
image

There also seems to be a problem with the z-index:
image

I'm also attaching a screenshot of the admin interface, where you could make a small adjustment to the navigation bar at the bottom. Make it look like the tutorial interface
image

We are making great progress, thank you again

**Comment by olilen** [comment]
Thank you for your recommendations, especially for the screenshots! 
I've fixed up the code according to your last comment.

I've also added some minor changes:
- changed the padding of the parent selector on the admin interface, so it has the same value around the content.
- changed the padding on the current step navigation buttons on the tutorial interface.

If you have any more recommendations or if you find any issues with the code, please let me know!

Thank you.

**Comment by sarkiroka** [comment]
I've found one more little thing, sorry I didn't mention it before. I am satisfied with the other parts, thank you very much for your contribution.

In the admin, when you try to remove a step:
image

**Review by Gyurmatag — APPROVED** [review]

**Pull request merged**
